// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXIbJS7dpXX7QknUuCV0xoc-SGazh8sk',
    appId: '1:1082095531255:web:12172d376245f8bf09cff2',
    messagingSenderId: '1082095531255',
    projectId: 'fir-authentication-f5793',
    authDomain: 'fir-authentication-f5793.firebaseapp.com',
    storageBucket: 'fir-authentication-f5793.appspot.com',
    measurementId: 'G-JM6ED7MXH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtHYR9M4-DmEZWl-TC1LiB5NRDwPq6guM',
    appId: '1:1082095531255:android:102bc9052324254609cff2',
    messagingSenderId: '1082095531255',
    projectId: 'fir-authentication-f5793',
    storageBucket: 'fir-authentication-f5793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0VhH6jj4hNtozOEhviCt3N4DKLa8oGE',
    appId: '1:1082095531255:ios:dc290a13f050279009cff2',
    messagingSenderId: '1082095531255',
    projectId: 'fir-authentication-f5793',
    storageBucket: 'fir-authentication-f5793.appspot.com',
    androidClientId: '1082095531255-pgo7l0qik4kgeie1jghudfkblnvic2lc.apps.googleusercontent.com',
    iosClientId: '1082095531255-jtr2p48hfchunct04fidntpnh4volq09.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU0VhH6jj4hNtozOEhviCt3N4DKLa8oGE',
    appId: '1:1082095531255:ios:dc290a13f050279009cff2',
    messagingSenderId: '1082095531255',
    projectId: 'fir-authentication-f5793',
    storageBucket: 'fir-authentication-f5793.appspot.com',
    androidClientId: '1082095531255-pgo7l0qik4kgeie1jghudfkblnvic2lc.apps.googleusercontent.com',
    iosClientId: '1082095531255-jtr2p48hfchunct04fidntpnh4volq09.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXXIbJS7dpXX7QknUuCV0xoc-SGazh8sk',
    appId: '1:1082095531255:web:e25f7f4265e51e7e09cff2',
    messagingSenderId: '1082095531255',
    projectId: 'fir-authentication-f5793',
    authDomain: 'fir-authentication-f5793.firebaseapp.com',
    storageBucket: 'fir-authentication-f5793.appspot.com',
    measurementId: 'G-BT7WV5818D',
  );

}